{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fox-control.fullname" . }}
  labels:
    {{- include "fox-control.labels" . | nindent 4 }}
type: Opaque
data:
  admin-secret: {{ .Values.auth.adminSecret | b64enc | quote }}
  instance-password: {{ .Values.auth.instancePassword | b64enc | quote }}
{{- end }}
